spring:
  profiles:
    active: dev
  datasource:
      name: demo
      url: jdbc:mysql://localhost:3306/localdemo?serverTimezone=GMT%2B8
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        initial-size: 1
        min-idle: 1
        max-active: 20
        test-on-borrow: true
        stat-view-servlet.allow: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.dao.model

mapper:
  mappers: com.example.demo.base.BaseMapper
  identity: MYSQL

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql